package org.northernnerds.enums;

public enum CommandTypes {

	SET_WARNING_HIGH, SET_WARNING_LOW, STATUS, SET_COOL, SET_HEAT, GET_ALARM_NUMBERS, SET_ALARM_NO_01, 
	SET_ALARM_NO_02, SET_ALARM_NO_03, SET_ALARM_NO_04, GET_BRANDS, SET_BRAND, SET_NAME, SET_PASSWORD;

	CommandTypes() {
	}
}
